//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

pub mod prelude;

pub mod audit_logs;
pub mod companies;
pub mod interviews;
pub mod materials;
pub mod meetings;
pub mod project_participants;
pub mod projects;
pub mod sessions;
pub mod students;
pub mod training_materials;
pub mod trainings;
pub mod users;
