//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

pub use super::audit_logs::Entity as AuditLogs;
pub use super::companies::Entity as Companies;
pub use super::interviews::Entity as Interviews;
pub use super::materials::Entity as Materials;
pub use super::meetings::Entity as Meetings;
pub use super::project_participants::Entity as ProjectParticipants;
pub use super::projects::Entity as Projects;
pub use super::sessions::Entity as Sessions;
pub use super::students::Entity as Students;
pub use super::training_materials::Entity as TrainingMaterials;
pub use super::trainings::Entity as Trainings;
pub use super::users::Entity as Users;
