//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "projects")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub training_id: Uuid,
    pub company_id: Uuid,
    pub title: String,
    pub start_date: Date,
    pub end_date: Date,
    pub created_by: i32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::companies::Entity",
        from = "Column::CompanyId",
        to = "super::companies::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Companies,
    #[sea_orm(has_many = "super::meetings::Entity")]
    Meetings,
    #[sea_orm(has_many = "super::project_participants::Entity")]
    ProjectParticipants,
    #[sea_orm(
        belongs_to = "super::trainings::Entity",
        from = "Column::TrainingId",
        to = "super::trainings::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Trainings,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedBy",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Users,
}

impl Related<super::companies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Companies.def()
    }
}

impl Related<super::meetings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Meetings.def()
    }
}

impl Related<super::project_participants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectParticipants.def()
    }
}

impl Related<super::trainings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Trainings.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}
